name: Make Bash script executable

on:
  push:
    branches: [ main ]

jobs:
  make-executable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x arch-install.sh
